name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install pascal compiler
      run:  |
        sudo apt-get install fp-compiler -y
    - name: Run a multi-line script
      run: |
        echo Add other actions to build
        ls -l $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        ls -l 
        fpc Menu.pas
