name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install pascal compiler
      run: apt-get -qq update && apt-get install fp-compiler -y
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        fpc Main.pas
